name: om-sys-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.25
  - pandas>=2.0
  - matplotlib>=3.8
  - scikit-learn>=1.3
  - nltk>=3.8.1
  - scikit-fuzzy>=0.4.2
  - pyyaml>=6.0
  - tqdm>=4.66
  - ipykernel
